spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: postgres
    password: password
  flyway:
    enabled: true
    locations: classpath:db/migration
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
